### PR TITLE
Cannot add new pin within the range of existing pin

### LINKED ISSUE #4: Should not add new pin within the range of existence pin
let the user cannot add another pin within the range of existence pin.

### PR DESCRIPTION
**Pull request by Shapokhan**
Fixes #4

### CODE REVIEW

**Comment by Shapokhan** [comment]
@omeryousaf I have created this branch from the issue-37 branch because in that branch I have fixed some issues related to the pin which I needed here in this branch.

**Comment by omeryousaf** [comment]
> @omeryousaf I have created this branch from the issue-37 branch because in that branch I have fixed some issues related to the pin which I needed here in this branch.

@Shapokhan feel free to merge master branch into this branch now cuz issue-37 has been merged into master now.

**Comment by Shapokhan** [comment]
> > @omeryousaf I have created this branch from the issue-37 branch because in that branch I have fixed some issues related to the pin which I needed here in this branch.
> 
> @Shapokhan feel free to merge master branch into this branch now cuz issue-37 has been merged into master now. That will make it more easy to see the changes made for this fix.

I checked out to the main branch and tried to "git pull origin main" but failed to git pull. 
Screenshot 2023-08-24 at 5 07 35 PM

**Comment by Shapokhan** [comment]
> > > @omeryousaf I have created this branch from the issue-37 branch because in that branch I have fixed some issues related to the pin which I needed here in this branch.
> > 
> > 
> > @Shapokhan feel free to merge master branch into this branch now cuz issue-37 has been merged into master now. That will make it more easy to see the changes made for this fix.
> 
> @omeryousaf I checked out to the main branch and tried to "git pull origin main" but failed to git pull. Screenshot 2023-08-24 at 5 07 35 PM

I have solved this problem. My local repository got corrupted so I cloned the project once again. It is working fine now.

**Comment by Shapokhan** [comment]
@omeryousaf this PR is waiting for your reveiw.

**Review by omeryousaf — APPROVED** [review]

**Pull request merged**
